
en:
        systemnameabbreviation: 'CoMS-Elektropribor'

        home: 'Home'
        pin: 'User&nbsp;info'
        conf: 'Conferences'
        lib: 'Library'
        adm: Admin

        systemname: 'Elektropribor Conference Management System'
        tos: Terms of Service

ru:
        systemnameabbreviation: 'СПОК-Электроприбор'

        home: 'Начало'
        pin: 'Пользователи'
        conf: 'Конференции'
        lib: 'Библиотека'
        adm: Админ

        systemname: 'Система Поддержки Организации Конференций ЦНИИ "Электроприбор"'
        tos: Пользовательское соглашение


