

development:
        mongo:
                host: localhost
                #host: s2.physcon.ru
                #dbname: ph3_dev
                dbname: coms
#        sphinx:
#                table: rt

test:

production:
        mongo:
                host: localhost
                #host: s2.physcon.ru
                dbname: coms
#        sphinx:
#                table: rt


